print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
no_people = int(input("How many people to split the bill? "))
final_amount = round(((bill*(tip/100))+bill)/no_people,2)
print(f"Each person should pay : ${final_amount}")
